# Generated by Django 2.2 on 2019-04-30 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='FOLDER NAME UNKNOWN', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=128)),
                ('content', models.TextField(default='')),
                ('is_question', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('good_questions', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ManyToManyField(default=0, related_name='post_folders', to='core.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='COURSE NAME UNKNOWN', max_length=128)),
                ('code', models.CharField(default='COURSE CODE UNKNOWN', max_length=128)),
                ('term', models.CharField(default='COURSE TERM UNKNOWN', max_length=128)),
                ('instructor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course_instructor', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(default=0, related_name='course_students', to=settings.AUTH_USER_MODEL)),
                ('ta_staff', models.ManyToManyField(default=0, related_name='course_TAs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
