# Generated by Django 2.1.7 on 2019-04-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190419_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ta_staff',
            field=models.ManyToManyField(default=0, related_name='course_TAs', to='core.TA'),
        ),
    ]
