# Generated by Django 2.2 on 2019-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190430_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instructor_answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='student_answer',
            field=models.TextField(default=''),
        ),
    ]
