# Generated by Django 2.1.7 on 2019-04-20 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190419_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='followups',
        ),
        migrations.AddField(
            model_name='followup',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='followup_post', to='core.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='folder',
            field=models.ManyToManyField(default=0, related_name='post_folders', to='core.Folder'),
        ),
    ]
