# Generated by Django 2.2 on 2019-05-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190501_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course_folders', to='core.Course'),
        ),
    ]
