# Generated by Django 2.1.7 on 2019-04-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190420_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='username',
        ),
    ]
